CREATE TABLE employee
(
id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
code            VARCHAR(255),
name             VARCHAR(255),
datee   VARCHAR(255),
grade            VARCHAR(255),
salary            VARCHAR(255),
PRIMARY KEY (id)
);