CREATE TABLE excelsheetentity
(
id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
code            VARCHAR(255),
name             VARCHAR(255),
todate            VARCHAR(255),
grade            VARCHAR(255),
salary            VARCHAR(255),
status            VARCHAR(255),
PRIMARY KEY (id)
);